version: '2'

services:
  server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python src/server.py
  db:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  testserver:
    env_file: .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 27017:27017
    environment:
      APPLICATION_PORT: 27017
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: mongo:3.6
