version: '2'

services:
  routine:
    env_file:
      - .env
    image: python:3.7
    links:
      - mongodb
    working_dir: /mnt
    volumes:
      - .:/mnt
    command: python src/main.py --debug
    ports:
      - 3000:3000

  mongodb:
    image: mongo:3.6
    ports:
        - 27017:27017
    volumes:
      - ./data/db:/data/db

  testroutine:
    env_file: .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testmongodb
    ports:
      - 27017:27017
    environment:
      APPLICATION_PORT: 27017
      APPLICATION_MONGODB_CONTAINER: testmongodb
    command: python -m pytest test/

  testmongodb:
    image: mongo:3.6
